# permissions for end users to view canarydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: canarydeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: canary-operator
    app.kubernetes.io/part-of: canary-operator
    app.kubernetes.io/managed-by: kustomize
  name: canarydeployment-viewer-role
rules:
- apiGroups:
  - canary.example.com
  resources:
  - canarydeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - canary.example.com
  resources:
  - canarydeployments/status
  verbs:
  - get
